import { Festival } from '@/types';

export const MOCK_CHELTENHAM: Festival = {
  id: 'cheltenham-2025',
  name: 'Cheltenham Festival 2025',
  course: 'Cheltenham',
  startDate: '2025-03-11',
  endDate: '2025-03-14',
  days: 4,
  races: [
    {
      id: 'day1-r1',
      name: "Supreme Novices' Hurdle",
      time: '2025-03-11T13:30:00Z',
      course: 'Cheltenham',
      day: 1,
      distance: '2m87y',
      grade: 'Grade 1',
      runners: [
        { id: 'h1', horseName: 'Brightwater', jockeyName: 'P. Townend', trainerName: 'W. Mullins', odds: 3.5, oddsDisplay: '5/2', form: '1-1-2', number: 1 },
        { id: 'h2', horseName: 'Lark In The Morn', jockeyName: 'R. Blackmore', trainerName: 'H. de Bromhead', odds: 5.0, oddsDisplay: '4/1', form: '1-1-1', number: 2 },
        { id: 'h3', horseName: 'Dysart Dynamo', jockeyName: 'D. Jacob', trainerName: 'W. Mullins', odds: 5.5, oddsDisplay: '9/2', form: '2-1-1', number: 3 },
        { id: 'h4', horseName: 'Facile Vega', jockeyName: 'M. Walsh', trainerName: 'W. Mullins', odds: 8.0, oddsDisplay: '7/1', form: '1-3-1', number: 4 },
        { id: 'h5', horseName: 'The Shunter', jockeyName: 'J. Burke', trainerName: 'E. Bolger', odds: 13.0, oddsDisplay: '12/1', form: '1-1-4', number: 5 },
        { id: 'h6', horseName: 'Redemption Day', jockeyName: 'H. Skelton', trainerName: 'D. Skelton', odds: 21.0, oddsDisplay: '20/1', form: '2-2-3', number: 6 },
        { id: 'h7', horseName: 'Stage Star', jockeyName: 'H. Cobden', trainerName: 'P. Nicholls', odds: 26.0, oddsDisplay: '25/1', form: '1-1-5', number: 7 },
      ],
    },
    {
      id: 'day1-r2',
      name: 'Arkle Challenge Trophy',
      time: '2025-03-11T14:10:00Z',
      course: 'Cheltenham',
      day: 1,
      distance: '1m7f199y',
      grade: 'Grade 1',
      runners: [
        { id: 'h8', horseName: 'El Fabiolo', jockeyName: 'P. Townend', trainerName: 'W. Mullins', odds: 3.0, oddsDisplay: '2/1', form: '1-1-1', number: 1 },
        { id: 'h9', horseName: 'Jonbon', jockeyName: 'N. de Boinville', trainerName: 'N. Henderson', odds: 4.0, oddsDisplay: '3/1', form: '1-1-2', number: 2 },
        { id: 'h10', horseName: "Riviere D'etel", jockeyName: 'R. Blackmore', trainerName: 'H. de Bromhead', odds: 4.5, oddsDisplay: '7/2', form: '1-2-1', number: 3 },
        { id: 'h11', horseName: 'Edwardstone', jockeyName: 'T. Cannon', trainerName: 'A. King', odds: 9.0, oddsDisplay: '8/1', form: '1-1-3', number: 4 },
        { id: 'h12', horseName: 'Blue Lord', jockeyName: 'M. Walsh', trainerName: 'W. Mullins', odds: 15.0, oddsDisplay: '14/1', form: '2-1-4', number: 5 },
      ],
    },
    {
      id: 'day2-r1',
      name: "Ballymore Novices' Hurdle",
      time: '2025-03-12T13:30:00Z',
      course: 'Cheltenham',
      day: 2,
      distance: '2m5f',
      grade: 'Grade 1',
      runners: [
        { id: 'h13', horseName: 'Corbetts Cross', jockeyName: 'R. Blackmore', trainerName: 'H. de Bromhead', odds: 4.0, oddsDisplay: '3/1', form: '1-1-1', number: 1 },
        { id: 'h14', horseName: 'Impaire Et Passe', jockeyName: 'M. Peltier', trainerName: 'E. Leenders', odds: 5.0, oddsDisplay: '4/1', form: '1-2-1', number: 2 },
        { id: 'h15', horseName: 'Stay Away Fay', jockeyName: 'P. Townend', trainerName: 'W. Mullins', odds: 5.5, oddsDisplay: '9/2', form: '1-1-2', number: 3 },
        { id: 'h16', horseName: 'Might I', jockeyName: 'D. Jacob', trainerName: 'W. Mullins', odds: 11.0, oddsDisplay: '10/1', form: '2-1-3', number: 4 },
        { id: 'h17', horseName: 'The Real Whacker', jockeyName: 'H. Cobden', trainerName: 'P. Nicholls', odds: 17.0, oddsDisplay: '16/1', form: '1-3-2', number: 5 },
      ],
    },
    {
      id: 'day3-r1',
      name: 'Ryanair Chase',
      time: '2025-03-13T14:50:00Z',
      course: 'Cheltenham',
      day: 3,
      distance: '2m4f127y',
      grade: 'Grade 1',
      runners: [
        { id: 'h18', horseName: 'Envoi Allen', jockeyName: 'R. Blackmore', trainerName: 'H. de Bromhead', odds: 2.75, oddsDisplay: '7/4', form: '1-2-1', number: 1 },
        { id: 'h19', horseName: 'Allaho', jockeyName: 'P. Townend', trainerName: 'W. Mullins', odds: 3.5, oddsDisplay: '5/2', form: '1-1-3', number: 2 },
        { id: 'h20', horseName: 'Conflated', jockeyName: 'D. Mullins', trainerName: 'G. Elliott', odds: 7.0, oddsDisplay: '6/1', form: '2-1-2', number: 3 },
        { id: 'h21', horseName: 'Imperial Aura', jockeyName: 'D. Jacob', trainerName: 'K. Bailey', odds: 10.0, oddsDisplay: '9/1', form: '1-3-1', number: 4 },
        { id: 'h22', horseName: 'Janidil', jockeyName: 'A. Zucchini', trainerName: 'W. Mullins', odds: 21.0, oddsDisplay: '20/1', form: '2-2-4', number: 5 },
      ],
    },
    {
      id: 'day4-r1',
      name: 'Cheltenham Gold Cup',
      time: '2025-03-14T15:30:00Z',
      course: 'Cheltenham',
      day: 4,
      distance: '3m2f46y',
      grade: 'Grade 1',
      runners: [
        { id: 'h23', horseName: 'Galopin Des Champs', jockeyName: 'P. Townend', trainerName: 'W. Mullins', odds: 2.5, oddsDisplay: '6/4', form: '1-1-1', number: 1 },
        { id: 'h24', horseName: 'Bravemansgame', jockeyName: 'H. Cobden', trainerName: 'P. Nicholls', odds: 5.0, oddsDisplay: '4/1', form: '1-2-1', number: 2 },
        { id: 'h25', horseName: 'Gerri Colombe', jockeyName: 'J. Codd', trainerName: 'G. Elliott', odds: 6.0, oddsDisplay: '5/1', form: '1-1-2', number: 3 },
        { id: 'h26', horseName: 'Royal Kahala', jockeyName: 'R. Blackmore', trainerName: 'H. de Bromhead', odds: 9.0, oddsDisplay: '8/1', form: '2-1-3', number: 4 },
        { id: 'h27', horseName: 'Ahoy Senor', jockeyName: 'D. Jacob', trainerName: 'L. Russell', odds: 15.0, oddsDisplay: '14/1', form: '2-2-1', number: 5 },
        { id: 'h28', horseName: 'Kildisart', jockeyName: 'S. Bowen', trainerName: 'B. Pauling', odds: 34.0, oddsDisplay: '33/1', form: '3-2-4', number: 6 },
      ],
    },
  ],
};
